const OTAs = {
    Facebook: 'facebook',
    iMessage: 'imessage',
    Local: 'cozrum',
    LocalWeb: 'cozrum.com',
    LocalExtend: 'cozrum_extend',
    SMS: 'sms',
    WhatsApp: 'whatsapp',
    Zalo: 'zalo',
    Airbnb: 'airbnb',
    Agoda: 'agoda',
    Booking: 'booking',
    Go2joy: 'go2joy',
    Google: 'google',
    Expedia: 'expedia',
    Luxstay: 'luxstay',
    Traveloka: 'traveloka',
    Grabhotel: 'grabhotel',
    Ctrip: 'ctrip',
    Tripi: 'tripi',
    Mytour: 'mytour',
    Quickstay: 'quickstay',
    TA: 'TA',
    Vrbo: 'vrbo',
    Vntrip: 'vntrip',
};

const SYS_CONST = Object.freeze({
    ASSET_DEFAULT_ATTRIBUTE: [
        {
            isDefault: true,
            name: 'Thông tin',
            type: 'String',
        },
        {
            isDefault: true,
            name: 'Đặc điểm',
            type: 'String',
        },
        {
            isDefault: true,
            name: 'Đơn vị tính',
            type: 'String',
        },
        {
            isDefault: true,
            name: 'Đơn giá',
            type: 'Number',
        },
        {
            isDefault: true,
            name: 'Số lượng',
            type: 'Number',
        },
        {
            isDefault: true,
            name: 'Hình ảnh thực tế',
            type: 'Images',
        },
        {
            isDefault: true,
            name: 'Hạn bảo hành',
            type: 'Date',
        },
        {
            isDefault: true,
            name: 'Phiếu bảo hành',
            type: 'Images',
        },
        {
            isDefault: true,
            name: 'Liên hệ bảo hành',
            type: 'String',
        },
        {
            isDefault: true,
            name: 'Ghi chú',
            type: 'String',
        },
    ],
    AUTO_EVENTS: ['Inquiry', 'Confirmed', 'Updated', 'Canceled', 'CheckIn', 'CheckOut'],
    BOOKING_ERRORS: {
        NEW_ROOM_NOT_AVAILABLE: 5001,
        NOT_AVAILABLE: 3001,
    },
    BOOKING_FEE: {
        PAY_AT_PROPERTY: 'pay_at_property',
    },
    BOOKING_LOG: {
        BOOKING_CANCLED: 'BOOKING_CANCLED',
        BOOKING_CANCLED_UNDO: 'BOOKING_CANCLED_UNDO',
        BOOKING_CREATE: 'BOOKING_CREATE',
        BOOKING_NOSHOW: 'BOOKING_NOSHOW',
        BOOKING_NOSHOW_UNDO: 'BOOKING_NOSHOW_UNDO',
        BOOKING_OVERBOOK: 'BOOKING_OVERBOOK',
        BOOKING_OVERBOOK_RESOLVED: 'BOOKING_OVERBOOK_RESOLVED',
        BOOKING_SPLIT: 'BOOKING_SPLIT',
        BOOKING_UPDATE_CHECKIN: 'BOOKING_UPDATE_CHECKIN',
        BOOKING_UPDATE_CHECKOUT: 'BOOKING_UPDATE_CHECKOUT',
        BOOKING_UPDATE_ROOM: 'BOOKING_UPDATE_ROOM',
        BOOKING_UPDATE_ROOM_AMOUNT: 'BOOKING_UPDATE_ROOM_AMOUNT',
        FEE_ELECTRIC_UPDATE: 'FEE_ELECTRIC_UPDATE',
        FEE_OTA_UPDATE: 'FEE_OTA_UPDATE',
        FEE_SERVICE_UPDATE: 'FEE_SERVICE_UPDATE',
        FEE_WATER_UPDATE: 'FEE_WATER_UPDATE',
        GUEST_CHECKIN: 'GUEST_CHECKIN',
        GUEST_CHECKIN_UNDO: 'GUEST_CHECKIN_UNDO',
        GUEST_CHECKOUT: 'GUEST_CHECKOUT',
        GUEST_CHECKOUT_UNDO: 'GUEST_CHECKOUT_UNDO',
        GUEST_LINKED: 'GUEST_LINKED',
        MESSAGE_LINK: 'MESSAGE_LINK',
        PRICE_UPDATE: 'PRICE_UPDATE',
        PRICE_UPDATE_AUTO: 'PRICE_UPDATE_AUTO',
        REQUEST_APPROVED: 'REQUEST_APPROVED',
        REQUEST_DECLINED: 'REQUEST_DECLINED',
    },
    BOOKING_STATUS: {
        CANCELED: 'canceled',
        CONFIRMED: 'confirmed',
        DECLINED: 'declined',
        NOSHOW: 'noshow',
        REQUEST: 'request',
    },
    CURRENCY: {
        USD: 'USD',
        VND: 'VND',
    },
    CURRENCY_CONVERT: {
        USD: 23101.99,
        VND: 1,
    },
    DESCRIPTION_TEMPLATE_TYPE: {
        PROPERTY: 'PROPERTY',
        ROOM: 'ROOM',
    },
    DIRECTION: {
        EAST: 'east',
        NORTH: 'north',
        NORTH_EAST: 'northeast',
        NORTH_WEST: 'northwest',
        SOUTH: 'south',
        SOUTH_EAST: 'southeast',
        SOUTH_WEST: 'southwest',
        WEST: 'west',
    },
    GENDER: {
        MALE: 'male',
        FEMALE: 'female',
        OTHER: 'other',
    },
    GUEST_TYPE: {
        ANONYMOUS: 'anonymous',
        NORMAL: 'normal',
    },
    INBOX_TYPE: {
        CANCELED: 'canceled',
        MESSAGE: 'message',
        REMINDER: 'reminder',
        RESERVATION: 'reservation',
        RESERVATION_ERROR: 'reservation_error',
        SMS: 'sms',
        TASK: 'task',
        RESERVATION_UPDATE: 'reservation_update',
    },
    LISTING_CONFIG: {
        [OTAs.Local]: { multiRooms: true },
        [OTAs.LocalWeb]: { multiRooms: true },
        [OTAs.Airbnb]: { multiRooms: false },
        [OTAs.Booking]: { multiRooms: true },
        [OTAs.Luxstay]: { multiRooms: false },
        [OTAs.Expedia]: { multiRooms: true },
        [OTAs.Vrbo]: { multiRooms: false },
        [OTAs.Vntrip]: { multiRooms: true },
        [OTAs.Agoda]: {
            multiRooms: true,
            USER_SENDER_ID: 10,
            HOST_SENDER_ID: 21,
            OTA_SENDER_ID: 11,
        },
        [OTAs.Traveloka]: { multiRooms: true },
        [OTAs.Ctrip]: { multiRooms: true },
        [OTAs.Tripi]: { multiRooms: true },
        [OTAs.Facebook]: { multiRooms: true },
        [OTAs.Grabhotel]: { multiRooms: true },
        [OTAs.Go2joy]: { multiRooms: true },
        [OTAs.Mytour]: { multiRooms: true },
        [OTAs.Quickstay]: { multiRooms: true },
    },
    LOCAL_OTA: OTAs.Local,
    LOCAL_OTAS: {
        LOCAL: OTAs.Local,
        EXTEND: OTAs.LocalExtend,
        ONLINE: OTAs.LocalWeb,
    },
    MESSAGE_ATTITUDE: {
        SATISFIED: 'satisfied',
        NORMAL: 'normal',
        UNSATISFIED: 'unsatisfied',
        ANGRY: 'angry',
    },
    MESSAGE_STATUS: {
        EVENT: 'event',
        NONE: 'none',
        REQUEST: 'request',
    },
    MESSAGE_VARIABLE: {
        GUEST: {
            description: 'Tên khách hàng',
            text: '%GUEST%',
        },
        GUIDE: {
            description: 'Guide check in',
            text: '%GUIDE%',
        },
    },
    ONE_DAY: 86400000,
    ONE_MINUTE: 60000,
    OTA_HAS_GENIUS: [OTAs.Booking, OTAs.Traveloka],
    OTA_HAS_NOT_RATE_PLAN: [OTAs.Airbnb, OTAs.Luxstay, OTAs.Traveloka, OTAs.Tripi, OTAs.Ctrip, OTAs.Grabhotel],
    OTAs,
    PAYOUT_SOURCE: {
        BANKING: 'banking',
        SWIPE_CARD: 'swipe_card',
        CASH: 'cash',
        VOUCHER: 'voucher',
        ONLINE_WALLET: 'online_wallet',
        THIRD_PARTY: 'third_party',
    },
    PAYOUT_STATE: {
        APPROVE: 'approve',
        APPROVE_2: 'approve_2',
        CONFIRMED: 'confirmed',
        CONFIRMED_2: 'confirmed_2',
        DELETED: 'deleted',
        PAID: 'paid',
        PAID_2: 'paid_2',
        PRE_CONFIRMED: 'pre_confirmed',
        PRE_CONFIRMED_2: 'pre_confirmed_2',
        PROCESSING: 'processing',
        TRANSFERRED: 'transferred',
    },
    PAYOUT_TYPE: {
        DEPOSIT: 'deposit',
        PAY: 'pay',
        PREPAID: 'prepaid',
        RESERVATION: 'reservation',
        SERVICE: 'service',
    },
    PAYOUT_TYPE_CODE: {
        pay: 'DC',
        prepaid: 'TU',
        reservation: 'HU',
    },
    PLACE_CONFIG: {
        DISTANCE: 300,
        MAX_DISTANCE: 1000,
    },
    PLATFORM: {
        WEB: 'web',
        WAP: 'wap',
        APP: 'app',
    },
    PROMOTION_TYPE: {
        BASIC: 'basic',
        EARLY_BIRD: 'early_booker',
        LAST_MINUTE: 'last_minute',
        RULE_SET: 'rule_set',
    },
    PROMOTION_TIME: {
        DAY: 'Day',
        HOUR: 'Hour',
    },
    PROMOTION_ACTION: {
        UPDATE: 'update',
        CLEAR: 'clear',
        SET: 'set',
    },
    PROPERTY_TYPE_SLUG: {
        1: 'service-apartment',
        2: 'condo',
        3: 'hotel',
        4: 'motel',
        5: 'dormitory',
        6: 'homestay',
        7: 'luxury-villa',
        9: 'lip-hotel',
    },
    RATE_DISCOUNT_TYPE: {
        AMOUNT: 'amount',
        PERCENTAGE: 'percentage',
    },
    ROOM_STATUS: {
        AVAILABLE: 'available',
        FULL: 'full',
    },
    RULE_DAY: {
        from: '14:00',
        to: '12:00',
    },
    RULE_HOUR: {
        openHour: '07:30',
        closeHour: '22:00',
        minHours: 1,
        maxHours: 7,
        firstHours: 1,
    },
    RULE_OVERNIGHT: {
        from: '22:00',
        openHour: '08:00',
        to: '12:00',
    },
    SERVICES: {
        DAY: 3,
        HOUR: 1,
        NIGHT: 2,
        MONTH: 4,
    },
    SERVICES_SLUG: {
        MONTH: 'cho-thue-dai-han',
        DAY: 'cho-thue-ngan-han',
        HOUR: 'cho-thue-theo-gio',
        NIGHT: 'cho-thue-qua-dem',
    },
    SETTINGS: {
        CURRENCY_EXCHANGE: {
            description: 'Exchange rate from USD to VND',
            key: 'CurrencyExchange',
            title: 'Exchange',
            value: 23101.99,
        },
        QR_CARD_ID: {
            description: 'Qr card ID',
            key: 'QRCardID',
            title: 'Qr card ID',
            value: 99,
        },
        AUTO_RESOLVE_OVERBOOK: {
            description: 'Auto resolve overbook',
            key: 'AutoResolveOverbook',
            title: 'AutoResolveOverbook',
            value: false,
        },
    },
    STRINGEE_TYPE: {
        SMS: 'sms',
        STRINGEE: 'stringee',
    },
    SUBDIVITION: {
        STREET: 'street',
        WARD: 'ward',
        DISTRICT: 'district',
        PROVINCE: 'province',
        COUNTRY: 'country',
    },
    TASK_STATUS: {
        CONFIRMED: 'confirmed',
        DELETED: 'deleted',
        DONE: 'done',
        WAITING: 'waiting',
    },
    TASK_TAG: {
        BUYING: 'buying',
        CLEANING: 'cleaning',
        COLLECT_MONEY: 'collect_money',
        CONFIRMATION_BOOKING: 'confirmation_booking',
        MAINTENANCE: 'maintenance',
        PA: 'pa',
        REPAIRING: 'repairing',
        TUTORIAL_CHECKIN: 'tutorial_checkin',
        VAT: 'vat',
    },
    THIRD_PARTY_PAYMENT: {
        MOMO: 'momo',
        VNPAY: 'vnpay',
    },
    USER_BOT: {
        ENGINE: 'cozrum_engine',
    },
    USER_ROLES: {
        ACCOUNTANT: 'ACCOUNTANT',
        ADMIN: 'ADMIN',
        ANONYMOUS: 'ANONYMOUS',
        CS: 'CS',
        CS_2: 'CS_2',
        HOST: 'HOST',
        LEADER: 'HOST_LEADER',
        MAID: 'MAID',
        MANAGER: 'MANAGER',
        MARKETING: 'MARKETING',
        REPAIRER: 'REPAIRER',
    },
    USER_ROLES_PERMISSONS: {
        ANONYMOUS: 'ANONYMOUS',
        BOOKING: 'BOOKING',
        CALLING: 'CALLING',
        CAMERA: 'CAMERA',
        INBOX: 'INBOX',
        INBOX_UNKNOWN_HIDDEN: 'INBOX_UNKNOWN_HIDDEN',
        RESERVATION: 'RESERVATION',
        ROOT: 'ROOT',
        SMS: 'SMS',
        SMS_MONEY_VIEW: 'SMS_MONEY_VIEW',
        TASK: 'TASK',
        TASK_STATUS_ONLY: 'TASK_STATUS_ONLY',
    },
    VAT: 0.08,
    WORK_NOTE_STATUS: {
        DOING: 'doing',
        DONE: 'done',
        CLOSED: 'closed',
    },
    DATA_TYPE: {
        ROOM: 'room',
        PROPERTY: 'property',
    },
    LANGUAGE: {
        VI: 'vi',
        EN: 'en',
        KO: 'ko',
        ZH: 'zh',
        JA: 'ja',
    },
});

module.exports = SYS_CONST;
